version: '3.7'
services:
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - 8000:8000
        depends_on:
            - db
            - redis
            - celery_worker
        links:
            - db:db
        entrypoint: /opt/app/web_auction/entrypoint.sh
        volumes:
            - /opt/app/web_auction/auction/migrations
    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=django_user
            - POSTGRES_PASSWORD=django_password
            - POSTGRES_DB=web_auction
    redis:
        image: "redis:alpine"
        ports:
            - 6379:6379
        environment:
            - REDIS_REPLICATION_MODE=master
    celery_worker:
        build: .
        command: celery -A web_auction worker -B -l INFO
        ports: []
        depends_on:
            - db
            - redis
        links:
            - db:db

volumes:
    postgres_data:
