# Generated by Django 2.0.4 on 2020-07-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('create_dt', models.DateTimeField(verbose_name='Created at')),
                ('close_dt', models.DateTimeField(verbose_name='Closing at')),
                ('start_bid', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Start bid, $')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Price, $')),
                ('description', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
