# Generated by Django 2.0.4 on 2020-07-01 16:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auto_20200701_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('bid_dt', models.DateTimeField(default=django.utils.timezone.now)),
                ('sum', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Sum, $')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.Item', verbose_name='Item title')),
            ],
        ),
    ]
