# Generated by Django 2.0.4 on 2020-07-01 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='sum',
            new_name='bid_value',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='item',
            new_name='item_id',
        ),
    ]
