# Generated by Django 2.0.4 on 2020-07-01 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auto_20200701_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid_value',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='username',
            new_name='user_name',
        ),
    ]
