# Generated by Django 2.0.4 on 2020-07-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_auto_20200701_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Sum, $'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Price, $'),
        ),
        migrations.AlterField(
            model_name='item',
            name='start_bid',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Start bid, $'),
        ),
    ]
