# Generated by Django 2.0.4 on 2020-07-04 09:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_remove_item_start_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_dt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Set at'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Bid value'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Price, $'),
        ),
    ]
