# Generated by Django 2.0.4 on 2020-07-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_auto_20200704_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deploy_name', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bid',
            name='user_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.TextField(),
        ),
    ]
