# Generated by Django 3.0.8 on 2020-07-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_auto_20200705_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='awarded_user',
            field=models.TextField(default=None, null=True, verbose_name='User awarded'),
        ),
    ]
