# Generated by Django 3.0.8 on 2020-07-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_item_awarded_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='awarded_user',
            field=models.TextField(default='', null=True, verbose_name='User awarded'),
        ),
    ]
