# Generated by Django 3.0.8 on 2020-07-28 22:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0012_item_expired'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('password', models.TextField()),
                ('role', models.TextField(default='user')),
                ('email', models.TextField()),
                ('autobid_total_sum', models.IntegerField(null=True)),
                ('autobid_sum_left', models.IntegerField(null=True)),
                ('autobid_alert_perc', models.IntegerField(default=95, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='bid',
            name='auto',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AutoBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Set at')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.Item', verbose_name='Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.AuctionUser', verbose_name='User')),
            ],
        ),
        migrations.AddField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auction.AuctionUser', verbose_name='User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='awarded_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.AuctionUser', verbose_name='User'),
        ),
    ]
